### ISSUE TITLE
Замечание

### ISSUE THREAD

**Issue by vkats-spbu** [Leonid-Lysenko/LabWork1#1]
Разделить на файлы

**Comment by Leonid-Lysenko** [comment]
Внес изменения

**Comment by AndreyIsakov01** [comment]
Выделение более 250% памяти

**Comment by Leonid-Lysenko** [comment]
Переделал лаб. работу полностью. Добавил, как просили, данные в класс. Проработал повороты и фильтр Гаусса

**Comment by Leonid-Lysenko** [comment]
Пожалуйста, если вас не затруднит, проверьте сегодня. Завтра я физически уже ничего не смогу исправить. 🙏

**Comment by vkats-spbu** [comment]
Оценка C. Перерасход памяти.
